FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build


FROM node:20-alpine

WORKDIR /app
RUN mkdir frontend
COPY --from=builder /app/.next/standalone /app/frontend
COPY --from=builder /app/.next/static /app/frontend/.next/static
COPY --from=builder /app/public /app/frontend/public

WORKDIR /app/frontend  
    
EXPOSE 3030
CMD ["node", "server.js"]